### PR TITLE
Correct import for Collection

### PR DESCRIPTION
**Pull request by Luukvdo**
Right now the getAllMeta function returns what seems to be an instance of Plank\Metable\Illuminate\Support\Collection.
This PR corrects that.

### CODE REVIEW

**Comment by frasmage** [comment]
Hi @Luukvdo,

Contributions to the documentation are always welcome! 

One nitpick, but that should actually be an `\Illuminate\Database\Eloquent\Collection`, a subclass of `Illuminate\Support\Collection`. I realize this was in my documentation to begin with. Since I assume your IDE is using the comments for static analysis, might as well give it the full feature set.

Would you like to make that correction? Then I will merge this.

**Comment by Luukvdo** [comment]
Hi @frasmage,

I made the change you requested along with some other PHPDoc changes

**Comment by frasmage** [comment]
@Luukvdo Thanks for you help. I will credit you in the changelog!

**Comment by Luukvdo** [comment]
Thanks 😄 

One small nitpick on the changelog. #8 was merged as well, but this isn't mentioned in the changelog yet

**Comment by frasmage** [comment]
Whoops! Sorry about that. Added a note about your contribution to the changelog and release notes.

**Pull request merged**
