### PR TITLE
Add Laravel 8.x support

### LINKED ISSUE #30: Laravel 8 support
Hi guys
I'm trying to update my Laravel to 8.x

but I have this issue 
https://share.getcloudapp.com/L1uJ2PYW

### PR DESCRIPTION
**Pull request by saulens22**
No notable changes in Laravel 8.0, so just dependencies version bump is required.

Closes #30

### CODE REVIEW

**Comment by frasmage** [comment]
Thank you for taking the initiative on this!

Not sure why the CI isn't posting to Github anymore, but this is failing to build, since laravel 8 pulls the model factories into it's own package:
https://travis-ci.org/github/plank/laravel-metable/jobs/725549330

**Comment by saulens22** [comment]
I replaced old factories into Laravel 8.x class based factories.
This will also require a bump to package versions so it's a breaking change.

Another solution would be to include `laravel/legacy-factories` in `require-dev`.

**Comment by frasmage** [comment]
I think I would prefer to maintain compatibility with Laravel versions >6.0 for now, so using the factory package would be preferable for now. 

We can drop PHP 7.2 support for now. That can be updated in the travis file.

**Comment by saulens22** [comment]
#32 does that. This pull request could be left for future version.

**Comment by frasmage** [comment]
Closing for now. Will re-evaluate once it is time to drop support for Laravel 6.0 and 7.0

**Pull request closed without merging**
