### PR TITLE
Allow Laravel framework v9

### PR DESCRIPTION
**Pull request by LeoColomb**
Laravel framework v9 is coming, first beta out.
Should probably be tested a bit.

### CODE REVIEW

**Comment by frasmage** [comment]
Just tried checking out and forcing those versions of Laravel and Testbench. I think there is a bug in the testbench version, I'm getting this on every testcase

```php
Error : Call to a member function merge() on array
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/laravel/config/app.php:193
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php:40
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php:24
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/src/Concerns/CreatesApplication.php:266
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/src/Concerns/CreatesApplication.php:228
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/src/TestCase.php:73
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/src/Concerns/Testing.php:81
 /Volumes/Development/laravel-metable/vendor/orchestra/testbench-core/src/TestCase.php:41
```

Probably too soon to merge

**Comment by LeoColomb** [comment]
@frasmage Thanks!
Yes, indeed, seems fixed upstream https://github.com/orchestral/testbench/issues/327
But Testbench v7 is not yet released, it is ok to wait a bit.

**Comment by frasmage** [comment]
Handled in #78

**Comment by LeoColomb** [comment]
Thanks for the update.
Keep in mind duplicating an existing PR without attribution is usually not very contributors friendly, especially when it is exactly the same.

**Comment by frasmage** [comment]
Used a separate PR as I was testing the permutations, but meant to credit you in the release notes. That was an oversight on my part that has been corrected. Thank you for your contribution 🙂

**Pull request closed without merging**
